name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t jouster-backend-test .

    - name: Run tests in Docker container
      run: |
        docker run --rm jouster-backend-test python -m pytest tests/ -v
